apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  
  POSTGRES_USER: YWRtaW4= # gitleaks:allow
  
  POSTGRES_PASSWORD: c2VjcmV0cGFzcw== # gitleaks:allow
  
  REDIS_PASSWORD: cmVkaXNwYXNz # gitleaks:allow